// Package adapters embeds the adapter catalog into the binary.
//
// The YAML files are the source of truth; index.gen.json is generated by
// `supermcp adapter index` and checked in CI to match.
package adapters

import "embed"

//go:embed */*/adapter.yaml index.gen.json
var FS embed.FS
