-- supermcp:breaking (rebuilds audit_events as a partitioned table, renames the
-- old one to audit_events_old; needs a major version and a maintenance window
-- with every replica stopped; docs/UPGRADING.md, "migration 00033")
-- +goose NO TRANSACTION
-- +goose Up

-- audit_events becomes a table partitioned by month on ts, so that
-- retention can remove a month of events by dropping its partition instead
-- of deleting its rows one by one. A delete of that size writes every row
-- to the WAL, leaves the space for autovacuum to find, and takes as long as
-- the month is large; a dropped partition is gone at commit.
--
-- ts is the partition key because it is the one timestamp the row has, the
-- application writes it (00008), the chain hash covers it, and nothing
-- updates it, so a row never moves between partitions. Months are UTC
-- calendar months. A row whose month has no partition (a clock far off, a
-- test ageing its stream) lands in audit_events_default rather than being
-- refused: refusing it would refuse the audit event. Creating the month's
-- partition later moves such rows into it.
--
-- What changes in the table's shape, because a partitioned table can only
-- enforce uniqueness over keys that include the partition key:
--
--   * The primary key is (seq, ts), not (seq). seq still comes from one
--     identity sequence for every partition, so it is still unique; the
--     database just no longer checks that on its own. Every query that
--     reads by seq (the writer's head, verify, anchors, the cut, the export
--     cursor, audit_search) leads with seq in the key and uses it per
--     partition.
--   * id is unique per (id, ts) rather than on its own. ids are UUIDv7
--     generated by the writer and nothing looks a row up by id.
--
-- Everything else is as it was: the columns and their order, defaults and
-- the outcome check; row-level security, forced, and its policy; the
-- application role's SELECT and its UPDATE of diff, payload and
-- scrubbed_at, and nothing more; and every index, declared on the parent so
-- each partition gets its own, audit_events_search_idx on the same
-- expression as 00027.
--
-- A partition is reached through audit_events and its policy, never on its
-- own. The default privileges from 00002 would give the application role
-- full access to each new partition, and a partition's own row-level
-- security is not the parent's, so audit_partition_ensure revokes
-- everything from the application role on every partition it creates, and
-- enables row-level security with no policy on it besides.
--
-- How the rows move, on a live table and resumably:
--
--   1. audit_events_new is created partitioned, with a partition for every
--      month from the oldest event to three months ahead.
--   2. Rows are copied in seq order, 50,000 per transaction, with the last
--      seq copied kept in audit_events_copy_progress. A rerun after a
--      failure continues from there.
--   3. The keys and indexes are built on the copy, once, which is faster
--      than keeping them up to date row by row.
--   4. One transaction takes audit_events under ACCESS EXCLUSIVE, copies
--      whatever was written since the last batch, carries the identity
--      sequence across, and swaps the names. The old table stays as
--      audit_events_old, readable by the maintenance role only, for the
--      operator to drop once `supermcp audit verify` passes. An empty one
--      (a new installation) is dropped here.
--
-- Updates to rows that were already copied are not carried: a scrub, a
-- legal hold or an erasure made by a running replica during step 2 would
-- be lost. That, and not the queries of the previous release, which run
-- against the new table unchanged, is why every replica is stopped for the
-- migration.
--
-- Three functions are left behind for the application:
-- audit_partition_bounds lists partitions and their months,
-- audit_partition_ensure creates missing months (the audit-partition-maint
-- job), and audit_events_cut removes everything at or below a retention
-- cut, dropping whole partitions where it can.

-- +goose StatementBegin
CREATE OR REPLACE FUNCTION audit_partition_bounds(p_parent regclass)
RETURNS TABLE (partition regclass, lower_bound timestamptz, upper_bound timestamptz)
LANGUAGE sql STABLE
SET search_path = pg_catalog, public, pg_temp
AS $f$
    -- The bounds are read back from the partition's own definition, which
    -- prints them in this session's time zone and date style and so parses
    -- back to the same instant here. The default partition has neither.
    SELECT c.oid::regclass,
           (pg_catalog.regexp_match(b, 'FROM \(''([^'']*)''\)'))[1]::timestamptz,
           (pg_catalog.regexp_match(b, 'TO \(''([^'']*)''\)'))[1]::timestamptz
    FROM pg_catalog.pg_inherits i
    JOIN pg_catalog.pg_class c ON c.oid = i.inhrelid
    CROSS JOIN LATERAL pg_catalog.pg_get_expr(c.relpartbound, c.oid) AS b
    WHERE i.inhparent = p_parent
    ORDER BY 2 NULLS FIRST
$f$;
-- +goose StatementEnd

-- audit_partition_ensure creates the monthly partitions of p_parent from
-- the month holding p_from through the month holding p_through that do not
-- exist yet, and returns how many it created. It is idempotent.
--
-- Each is created on its own and attached, rather than with CREATE TABLE
-- ... PARTITION OF, which would take ACCESS EXCLUSIVE on audit_events and
-- stop every append while it waited. ATTACH takes SHARE UPDATE EXCLUSIVE,
-- which appends and reads do not conflict with; the CHECK added first lets
-- it skip scanning the new table. Rows the default partition holds for the
-- month are moved in first, or the attach would refuse.
-- +goose StatementBegin
CREATE OR REPLACE FUNCTION audit_partition_ensure(p_parent regclass, p_from timestamptz, p_through timestamptz)
RETURNS integer
LANGUAGE plpgsql
SET search_path = pg_catalog, public, pg_temp
SET TimeZone = 'UTC'
AS $f$
DECLARE
    lo timestamptz := date_trunc('month', p_from);
    hi timestamptz;
    name text;
    def regclass;
    created integer := 0;
BEGIN
    SELECT NULLIF(partdefid, 0)::regclass INTO def FROM pg_partitioned_table WHERE partrelid = p_parent;
    WHILE lo <= p_through LOOP
        hi := lo + interval '1 month';
        name := 'audit_events_p' || to_char(lo, 'YYYYMM');
        IF to_regclass('public.' || quote_ident(name)) IS NULL THEN
            EXECUTE format('CREATE TABLE public.%I (LIKE %s INCLUDING DEFAULTS INCLUDING CONSTRAINTS INCLUDING STORAGE)',
                name, p_parent);
            EXECUTE format('ALTER TABLE public.%I ADD CONSTRAINT %I CHECK (ts >= %L AND ts < %L)',
                name, name || '_bound', lo, hi);
            IF def IS NOT NULL THEN
                EXECUTE format('WITH moved AS (DELETE FROM %s WHERE ts >= $1 AND ts < $2 RETURNING *) '
                    'INSERT INTO public.%I OVERRIDING SYSTEM VALUE SELECT * FROM moved', def, name) USING lo, hi;
            END IF;
            EXECUTE format('REVOKE ALL ON public.%I FROM PUBLIC, supermcp_app', name);
            EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', name);
            EXECUTE format('ALTER TABLE %s ATTACH PARTITION public.%I FOR VALUES FROM (%L) TO (%L)',
                p_parent, name, lo, hi);
            EXECUTE format('ALTER TABLE public.%I DROP CONSTRAINT %I', name, name || '_bound');
            created := created + 1;
        END IF;
        lo := hi;
    END LOOP;
    RETURN created;
END
$f$;
-- +goose StatementEnd

-- audit_events_cut removes every event at or below p_cut_seq, the
-- retention cut Reader.Cut has chosen and anchored in the same
-- transaction. A partition whose month ended before p_before and that
-- holds nothing above the cut is dropped whole; the rest lose their rows
-- at or below the cut one by one. What is removed is the same prefix of the
-- chain either way, so the anchor bridges it the same way. It returns how
-- many events went and which partitions.
--
-- The rows go first, under the lock any delete takes. Only then are the
-- whole partitions detached and dropped, which needs ACCESS EXCLUSIVE on
-- audit_events: the chain lock the writer appends under is taken first, so
-- appends wait on that rather than queue behind the table lock, and both
-- give up after p_lock_timeout. A reader holding the table (a long verify
-- or export) therefore fails the cut, which is rolled back whole and tried
-- again on the next sweep.
-- +goose StatementBegin
CREATE OR REPLACE FUNCTION audit_events_cut(p_cut_seq bigint, p_before timestamptz, p_chain_lock bigint, p_lock_timeout text)
RETURNS TABLE (deleted bigint, dropped text[])
LANGUAGE plpgsql
SET search_path = pg_catalog, public, pg_temp
AS $f$
DECLARE
    part record;
    whole regclass[] := '{}';
    rest regclass[] := '{}';
    p regclass;
    above boolean;
    n bigint;
BEGIN
    deleted := 0;
    dropped := '{}';
    FOR part IN SELECT * FROM public.audit_partition_bounds('public.audit_events'::regclass) LOOP
        IF part.upper_bound IS NOT NULL AND part.upper_bound <= p_before THEN
            EXECUTE format('SELECT EXISTS (SELECT 1 FROM %s WHERE seq > $1)', part.partition) INTO above USING p_cut_seq;
            IF NOT above THEN
                whole := whole || part.partition;
                CONTINUE;
            END IF;
        END IF;
        rest := rest || part.partition;
    END LOOP;

    FOREACH p IN ARRAY rest LOOP
        EXECUTE format('DELETE FROM %s WHERE seq <= $1', p) USING p_cut_seq;
        GET DIAGNOSTICS n = ROW_COUNT;
        deleted := deleted + n;
    END LOOP;

    IF cardinality(whole) > 0 THEN
        PERFORM set_config('lock_timeout', p_lock_timeout, true);
        PERFORM pg_advisory_xact_lock(p_chain_lock);
        LOCK TABLE public.audit_events IN ACCESS EXCLUSIVE MODE;
        FOREACH p IN ARRAY whole LOOP
            EXECUTE format('SELECT count(*) FROM %s', p) INTO n;
            deleted := deleted + n;
            dropped := dropped || p::text;
            EXECUTE format('ALTER TABLE public.audit_events DETACH PARTITION %s', p);
            EXECUTE format('DROP TABLE %s', p);
        END LOOP;
    END IF;
    RETURN NEXT;
END
$f$;
-- +goose StatementEnd

REVOKE ALL ON FUNCTION audit_partition_bounds(regclass) FROM PUBLIC;
REVOKE ALL ON FUNCTION audit_partition_ensure(regclass, timestamptz, timestamptz) FROM PUBLIC;
REVOKE ALL ON FUNCTION audit_events_cut(bigint, timestamptz, bigint, text) FROM PUBLIC;

-- 1. The partitioned copy, its partitions, and where the copy has got to.
-- Nothing here runs once the swap has happened, so a rerun after it is a
-- no-op.
-- +goose StatementBegin
DO $new$
DECLARE
    oldest timestamptz;
BEGIN
    IF (SELECT relkind FROM pg_class WHERE oid = 'public.audit_events'::regclass) = 'p' THEN
        RETURN;
    END IF;
    -- Left by an earlier upgrade that was then migrated down. The swap
    -- would need its name, and it may be the only copy of something.
    IF to_regclass('public.audit_events_old') IS NOT NULL THEN
        RAISE EXCEPTION 'audit_events_old is still here from an earlier upgrade'
            USING HINT = 'Drop it, or rename it if you want to keep it, and run the migration again. docs/UPGRADING.md, migration 00033.';
    END IF;
    IF to_regclass('public.audit_events_new') IS NULL THEN
        CREATE TABLE audit_events_new (
            seq             bigint GENERATED ALWAYS AS IDENTITY,
            id              uuid NOT NULL,
            ts              timestamptz NOT NULL,
            organization_id text,
            category        text NOT NULL,
            action          text NOT NULL,
            outcome         text NOT NULL,
            actor_kind      text NOT NULL,
            actor_id        text,
            actor_display   text NOT NULL DEFAULT '',
            on_behalf_of    text,
            target_kind     text,
            target_id       text,
            target_display  text NOT NULL DEFAULT '',
            request_id      text,
            session_id      text,
            ip              inet,
            user_agent      text,
            diff            json,
            payload         json,
            meta            json,
            prev_hash       bytea NOT NULL,
            hash            bytea NOT NULL,
            legal_hold      boolean NOT NULL DEFAULT false,
            content_hash    bytea NOT NULL,
            scrubbed_at     timestamptz,
            CONSTRAINT audit_events_new_outcome_check CHECK (outcome IN ('success', 'failure', 'denied', 'pending'))
        ) PARTITION BY RANGE (ts);

        ALTER TABLE audit_events_new ENABLE ROW LEVEL SECURITY;
        ALTER TABLE audit_events_new FORCE ROW LEVEL SECURITY;
        CREATE POLICY org_isolation ON audit_events_new FOR SELECT USING (organization_id = current_org());
        -- The default privileges from 00002 granted the application role
        -- everything; it gets back exactly what it had on audit_events.
        REVOKE ALL ON audit_events_new FROM PUBLIC, supermcp_app;
        GRANT SELECT ON audit_events_new TO supermcp_app;
        GRANT UPDATE (diff, payload, scrubbed_at) ON audit_events_new TO supermcp_app;

        CREATE TABLE audit_events_default PARTITION OF audit_events_new DEFAULT;
        REVOKE ALL ON audit_events_default FROM PUBLIC, supermcp_app;
        ALTER TABLE audit_events_default ENABLE ROW LEVEL SECURITY;
    END IF;

    IF to_regclass('public.audit_events_copy_progress') IS NULL THEN
        CREATE TABLE audit_events_copy_progress (copied_through bigint NOT NULL);
        INSERT INTO audit_events_copy_progress VALUES (0);
        REVOKE ALL ON audit_events_copy_progress FROM PUBLIC, supermcp_app;
    END IF;

    -- One read of ts over the whole table. The oldest by seq is not
    -- necessarily the oldest by time, and a month missed here would put
    -- its rows in the default partition.
    SELECT min(ts) INTO oldest FROM audit_events;
    PERFORM audit_partition_ensure('public.audit_events_new'::regclass,
        LEAST(COALESCE(oldest, now()), now()), now() + interval '3 months');
END
$new$;
-- +goose StatementEnd

-- 2. The copy. A procedure, because it commits after each batch: a failure
-- loses one batch of work, not all of it, and a rerun continues from the
-- progress row. OVERRIDING SYSTEM VALUE keeps every seq as it was; the
-- chain is keyed on it.
-- +goose StatementBegin
-- No SET search_path on it: a procedure with a SET clause may not commit.
CREATE OR REPLACE PROCEDURE audit_events_copy_batches(p_batch integer)
LANGUAGE plpgsql
AS $p$
DECLARE
    done bigint;
    upto bigint;
BEGIN
    IF to_regclass('public.audit_events_copy_progress') IS NULL THEN
        RETURN;
    END IF;
    LOOP
        SELECT copied_through INTO done FROM audit_events_copy_progress;
        SELECT max(seq) INTO upto FROM (
            SELECT seq FROM audit_events WHERE seq > done ORDER BY seq LIMIT p_batch) s;
        EXIT WHEN upto IS NULL;
        INSERT INTO audit_events_new (seq, id, ts, organization_id, category, action, outcome, actor_kind,
            actor_id, actor_display, on_behalf_of, target_kind, target_id, target_display, request_id,
            session_id, ip, user_agent, diff, payload, meta, prev_hash, hash, legal_hold, content_hash, scrubbed_at)
        OVERRIDING SYSTEM VALUE
        SELECT seq, id, ts, organization_id, category, action, outcome, actor_kind,
            actor_id, actor_display, on_behalf_of, target_kind, target_id, target_display, request_id,
            session_id, ip, user_agent, diff, payload, meta, prev_hash, hash, legal_hold, content_hash, scrubbed_at
        FROM audit_events WHERE seq > done AND seq <= upto;
        UPDATE audit_events_copy_progress SET copied_through = upto;
        COMMIT;
    END LOOP;
END
$p$;
-- +goose StatementEnd

CALL audit_events_copy_batches(50000);

-- 3. Keys and indexes, on the parent, so every partition has them and
-- every partition created later gets them. Not CONCURRENTLY: nothing
-- reads or writes audit_events_new yet. Each statement is its own
-- transaction, so a rerun skips what was built.
-- +goose StatementBegin
DO $keys$
BEGIN
    IF (SELECT relkind FROM pg_class WHERE oid = 'public.audit_events'::regclass) = 'p' THEN
        RETURN;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'audit_events_new_pkey') THEN
        ALTER TABLE audit_events_new ADD CONSTRAINT audit_events_new_pkey PRIMARY KEY (seq, ts);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'audit_events_new_id_key') THEN
        ALTER TABLE audit_events_new ADD CONSTRAINT audit_events_new_id_key UNIQUE (id, ts);
    END IF;
END
$keys$;
-- +goose StatementEnd

CREATE INDEX IF NOT EXISTS audit_events_new_org_time_idx ON audit_events_new (organization_id, ts DESC);
CREATE INDEX IF NOT EXISTS audit_events_new_action_idx ON audit_events_new (organization_id, category, action, ts DESC);
CREATE INDEX IF NOT EXISTS audit_events_new_actor_idx ON audit_events_new (actor_id, ts DESC);
CREATE INDEX IF NOT EXISTS audit_events_new_target_idx ON audit_events_new (target_kind, target_id, ts DESC);
CREATE INDEX IF NOT EXISTS audit_events_new_org_seq_idx ON audit_events_new (organization_id, seq);
CREATE INDEX IF NOT EXISTS audit_events_new_search_idx ON audit_events_new
    USING gin (audit_search_document(action, actor_id, actor_display, target_kind, target_id, target_display, meta));

-- 4. The swap, in one transaction. ACCESS EXCLUSIVE on the old table for
-- as long as the tail copy and the renames take: with the replicas
-- stopped there is no tail, and it is a matter of milliseconds.
-- +goose StatementBegin
DO $swap$
DECLARE
    done bigint;
    oldseq text;
    last bigint;
    called boolean;
BEGIN
    IF (SELECT relkind FROM pg_class WHERE oid = 'public.audit_events'::regclass) = 'p' THEN
        RETURN;
    END IF;
    LOCK TABLE audit_events IN ACCESS EXCLUSIVE MODE;

    SELECT copied_through INTO done FROM audit_events_copy_progress;
    INSERT INTO audit_events_new (seq, id, ts, organization_id, category, action, outcome, actor_kind,
        actor_id, actor_display, on_behalf_of, target_kind, target_id, target_display, request_id,
        session_id, ip, user_agent, diff, payload, meta, prev_hash, hash, legal_hold, content_hash, scrubbed_at)
    OVERRIDING SYSTEM VALUE
    SELECT seq, id, ts, organization_id, category, action, outcome, actor_kind,
        actor_id, actor_display, on_behalf_of, target_kind, target_id, target_display, request_id,
        session_id, ip, user_agent, diff, payload, meta, prev_hash, hash, legal_hold, content_hash, scrubbed_at
    FROM audit_events WHERE seq > done;

    -- The next event takes the number the old table would have given it.
    oldseq := pg_get_serial_sequence('public.audit_events', 'seq');
    EXECUTE format('SELECT last_value, is_called FROM %s', oldseq) INTO last, called;
    PERFORM setval(pg_get_serial_sequence('public.audit_events_new', 'seq'), last, called);

    ALTER TABLE audit_events RENAME TO audit_events_old;
    ALTER TABLE audit_events_old RENAME CONSTRAINT audit_events_pkey TO audit_events_old_pkey;
    ALTER TABLE audit_events_old RENAME CONSTRAINT audit_events_id_key TO audit_events_old_id_key;
    ALTER TABLE audit_events_old RENAME CONSTRAINT audit_events_outcome_check TO audit_events_old_outcome_check;
    ALTER INDEX audit_events_org_time_idx RENAME TO audit_events_old_org_time_idx;
    ALTER INDEX audit_events_action_idx RENAME TO audit_events_old_action_idx;
    ALTER INDEX audit_events_actor_idx RENAME TO audit_events_old_actor_idx;
    ALTER INDEX audit_events_target_idx RENAME TO audit_events_old_target_idx;
    ALTER INDEX IF EXISTS audit_events_org_seq_idx RENAME TO audit_events_old_org_seq_idx;
    ALTER INDEX IF EXISTS audit_events_search_idx RENAME TO audit_events_old_search_idx;
    ALTER SEQUENCE audit_events_seq_seq RENAME TO audit_events_old_seq_seq;
    -- The copy is the record now. The old table is kept for the operator
    -- to compare against and drop, not for the application to read.
    REVOKE ALL ON audit_events_old FROM PUBLIC, supermcp_app;

    ALTER TABLE audit_events_new RENAME TO audit_events;
    ALTER TABLE audit_events RENAME CONSTRAINT audit_events_new_pkey TO audit_events_pkey;
    ALTER TABLE audit_events RENAME CONSTRAINT audit_events_new_id_key TO audit_events_id_key;
    ALTER TABLE audit_events RENAME CONSTRAINT audit_events_new_outcome_check TO audit_events_outcome_check;
    ALTER INDEX audit_events_new_org_time_idx RENAME TO audit_events_org_time_idx;
    ALTER INDEX audit_events_new_action_idx RENAME TO audit_events_action_idx;
    ALTER INDEX audit_events_new_actor_idx RENAME TO audit_events_actor_idx;
    ALTER INDEX audit_events_new_target_idx RENAME TO audit_events_target_idx;
    ALTER INDEX audit_events_new_org_seq_idx RENAME TO audit_events_org_seq_idx;
    ALTER INDEX audit_events_new_search_idx RENAME TO audit_events_search_idx;
    ALTER SEQUENCE audit_events_new_seq_seq RENAME TO audit_events_seq_seq;

    DROP TABLE audit_events_copy_progress;
    -- A new installation has nothing to compare against.
    IF NOT EXISTS (SELECT 1 FROM audit_events_old) THEN
        DROP TABLE audit_events_old;
    END IF;
END
$swap$;
-- +goose StatementEnd

DROP PROCEDURE IF EXISTS audit_events_copy_batches(integer);

-- +goose Down

-- Back to one plain table, built from the partitioned one so that what was
-- written, scrubbed, held or cut since the upgrade is what comes back.
-- audit_events_old, if it is still there, is left alone. Like the way up,
-- this wants every replica stopped; it is not resumable, and a failure
-- rolls back to the partitioned table.
-- +goose StatementBegin
DO $down$
DECLARE
    last bigint;
    called boolean;
BEGIN
    IF (SELECT relkind FROM pg_class WHERE oid = 'public.audit_events'::regclass) <> 'p' THEN
        RETURN;
    END IF;
    LOCK TABLE audit_events IN ACCESS EXCLUSIVE MODE;
    CREATE TABLE audit_events_plain (
        seq             bigint GENERATED ALWAYS AS IDENTITY,
        id              uuid NOT NULL,
        ts              timestamptz NOT NULL,
        organization_id text,
        category        text NOT NULL,
        action          text NOT NULL,
        outcome         text NOT NULL,
        actor_kind      text NOT NULL,
        actor_id        text,
        actor_display   text NOT NULL DEFAULT '',
        on_behalf_of    text,
        target_kind     text,
        target_id       text,
        target_display  text NOT NULL DEFAULT '',
        request_id      text,
        session_id      text,
        ip              inet,
        user_agent      text,
        diff            json,
        payload         json,
        meta            json,
        prev_hash       bytea NOT NULL,
        hash            bytea NOT NULL,
        legal_hold      boolean NOT NULL DEFAULT false,
        content_hash    bytea NOT NULL,
        scrubbed_at     timestamptz
    );
    INSERT INTO audit_events_plain OVERRIDING SYSTEM VALUE SELECT * FROM audit_events ORDER BY seq;
    SELECT last_value, is_called INTO last, called FROM audit_events_seq_seq;

    DROP TABLE audit_events;
    ALTER TABLE audit_events_plain RENAME TO audit_events;
    ALTER SEQUENCE audit_events_plain_seq_seq RENAME TO audit_events_seq_seq;
    PERFORM setval('public.audit_events_seq_seq', last, called);
    ALTER TABLE audit_events ADD CONSTRAINT audit_events_pkey PRIMARY KEY (seq);
    ALTER TABLE audit_events ADD CONSTRAINT audit_events_id_key UNIQUE (id);
    ALTER TABLE audit_events ADD CONSTRAINT audit_events_outcome_check
        CHECK (outcome IN ('success', 'failure', 'denied', 'pending'));
    CREATE INDEX audit_events_org_time_idx ON audit_events (organization_id, ts DESC);
    CREATE INDEX audit_events_action_idx ON audit_events (organization_id, category, action, ts DESC);
    CREATE INDEX audit_events_actor_idx ON audit_events (actor_id, ts DESC);
    CREATE INDEX audit_events_target_idx ON audit_events (target_kind, target_id, ts DESC);
    CREATE INDEX audit_events_org_seq_idx ON audit_events (organization_id, seq);
    CREATE INDEX audit_events_search_idx ON audit_events
        USING gin (audit_search_document(action, actor_id, actor_display, target_kind, target_id, target_display, meta));

    ALTER TABLE audit_events ENABLE ROW LEVEL SECURITY;
    ALTER TABLE audit_events FORCE ROW LEVEL SECURITY;
    CREATE POLICY org_isolation ON audit_events FOR SELECT USING (organization_id = current_org());
    REVOKE ALL ON audit_events FROM PUBLIC, supermcp_app;
    GRANT SELECT ON audit_events TO supermcp_app;
    GRANT UPDATE (diff, payload, scrubbed_at) ON audit_events TO supermcp_app;
END
$down$;
-- +goose StatementEnd

DROP PROCEDURE IF EXISTS audit_events_copy_batches(integer);
DROP FUNCTION IF EXISTS audit_events_cut(bigint, timestamptz, bigint, text);
DROP FUNCTION IF EXISTS audit_partition_ensure(regclass, timestamptz, timestamptz);
DROP FUNCTION IF EXISTS audit_partition_bounds(regclass);
