-- supermcp:breaking (rebuilds audit_events as a partitioned table, renames the
-- old one to audit_events_old; needs a major version and a maintenance window
-- with every replica stopped; docs/UPGRADING.md, "migration 00033")
-- +goose NO TRANSACTION
-- +goose Up

-- audit_events becomes a table partitioned by month on ts, so that
-- retention can remove a month of events by dropping its partition instead
-- of deleting its rows one by one. A delete of that size writes every row
-- to the WAL, leaves the space for autovacuum to find, and takes as long as
-- the month is large; a dropped partition is gone at commit.
--
-- ts is the partition key because it is the one timestamp the row has, the
-- application writes it (00008), the chain hash covers it, and nothing
-- updates it, so a row never moves between partitions. Months are UTC
-- calendar months. A row whose month has no partition (a clock far off, a
-- test ageing its stream) lands in audit_events_default rather than being
-- refused: refusing it would refuse the audit event. Creating the month's
-- partition later moves such rows into it.
--
-- What changes in the table's shape, because a partitioned table can only
-- enforce uniqueness over keys that include the partition key:
--
--   * The primary key is (seq, ts), not (seq). seq still comes from one
--     identity sequence for every partition, so it is still unique; the
--     database just no longer checks that on its own. Every query that
--     reads by seq (the writer's head, verify, anchors, the cut, the export
--     cursor, audit_search) leads with seq in the key and uses it per
--     partition.
--   * id is unique per (id, ts) rather than on its own. ids are UUIDv7
--     generated by the writer and nothing looks a row up by id.
--
-- One index is new: audit_events_legal_hold_idx, on seq for held rows only.
-- The cut asks for the lowest held row on every sweep, and asks again under
-- the table lock before it drops a month; without it both read the whole
-- trail. Holds are rare, so it costs next to nothing to keep.
--
-- Everything else is as it was: the columns and their order, defaults and
-- the outcome check; row-level security, forced, and its policy; the
-- application role's SELECT and its UPDATE of diff, payload and
-- scrubbed_at, and nothing more; and every index, declared on the parent so
-- each partition gets its own, audit_events_search_idx on the same
-- expression as 00027.
--
-- A partition is reached through audit_events and its policy, never on its
-- own. The default privileges from 00002 would give the application role
-- full access to each new partition, and a partition's own row-level
-- security is not the parent's, so audit_partition_ensure revokes
-- everything from the application role on every partition it creates, and
-- enables row-level security with no policy on it besides.
--
-- How the rows move, resumably:
--
--   1. audit_events_new is created partitioned, with a partition for every
--      month from the oldest event to three months ahead.
--   2. Rows are copied in seq order, 50,000 per transaction, with the last
--      seq copied kept in audit_events_copy_progress. A rerun after a
--      failure continues from there.
--   3. The keys and indexes are built on the copy, once, which is faster
--      than keeping them up to date row by row.
--   4. One transaction takes audit_events under ACCESS EXCLUSIVE, copies
--      whatever was written since the last batch, brings the copied rows'
--      mutable columns up to date, carries the identity sequence across,
--      and swaps the names. The old table stays as audit_events_old,
--      readable by the maintenance role only, for the operator to drop
--      once `supermcp audit verify` passes. An empty one (a new
--      installation) is dropped here.
--
-- Every replica must be stopped first. A running one would scrub, place a
-- legal hold on, or pseudonymise (supermcp dsar erase) rows that have
-- already been copied; a lost hold lets a later cut delete what it
-- protected, and a lost erasure brings a name back. Two defences:
--
--   * audit_events_migration_guard, at the start of the copy and again at
--     the swap, refuses to go on while any other session of the application
--     is connected: a client session in this database, other than the
--     migrator's own (application_name supermcp-migrate, internal/store),
--     whose role is a member of supermcp_app or that is listening for
--     cache invalidations. An empty trail has nothing to lose, so a new
--     installation is not checked.
--   * The swap, holding the lock, copies diff, payload, scrubbed_at,
--     legal_hold, actor_display and target_display again from the old
--     table wherever they differ, and removes copied rows the old table no
--     longer has. What changed during the copy therefore reaches the copy
--     even if the guard was got round.
--
-- Three functions are left behind for the application:
-- audit_partition_bounds lists partitions and their months,
-- audit_partition_ensure creates missing months (the audit-partition-maint
-- job), and audit_events_cut removes everything at or below a retention
-- cut, dropping whole partitions where it can.
--
-- Two settings exist for the migration test (internal/store), not for
-- operators: supermcp.audit_copy_batch, the rows per batch (50,000), and
-- supermcp.audit_copy_batches, how many batches this run copies before it
-- stops with an error, as a failure would.

-- +goose StatementBegin
CREATE OR REPLACE FUNCTION audit_partition_bounds(p_parent regclass)
RETURNS TABLE (partition regclass, lower_bound timestamptz, upper_bound timestamptz)
LANGUAGE sql STABLE
SET search_path = pg_catalog, public, pg_temp
AS $f$
    -- The bounds are read back from the partition's own definition, which
    -- prints them in this session's time zone and date style and so parses
    -- back to the same instant here. The default partition has neither.
    SELECT c.oid::regclass,
           (pg_catalog.regexp_match(b, 'FROM \(''([^'']*)''\)'))[1]::timestamptz,
           (pg_catalog.regexp_match(b, 'TO \(''([^'']*)''\)'))[1]::timestamptz
    FROM pg_catalog.pg_inherits i
    JOIN pg_catalog.pg_class c ON c.oid = i.inhrelid
    CROSS JOIN LATERAL pg_catalog.pg_get_expr(c.relpartbound, c.oid) AS b
    WHERE i.inhparent = p_parent
    ORDER BY 2 NULLS FIRST
$f$;
-- +goose StatementEnd

-- audit_partition_ensure creates the monthly partitions of p_parent from
-- the month holding p_from through the month holding p_through that do not
-- exist yet, and returns how many it created. It is idempotent. A table of
-- a month's name that exists but is not attached is an error, not skipped:
-- it would leave the month in the default partition for ever.
--
-- Each is created on its own and attached, rather than with CREATE TABLE
-- ... PARTITION OF, which would take ACCESS EXCLUSIVE on audit_events and
-- stop every append while it waited. ATTACH takes SHARE UPDATE EXCLUSIVE
-- on audit_events, which appends and reads do not conflict with; the CHECK
-- added first lets it skip scanning the new table. It does take ACCESS
-- EXCLUSIVE on audit_events_default, which it scans to prove none of its
-- rows belong to the month, so for as long as that takes, and for as long
-- as it waits for the lock, a query that cannot rule out the default
-- partition (any read not bounded by ts, an append to it) waits too. The
-- rows the default partition holds for the month are moved first, or the
-- attach would refuse; normally there are none and all of it is quick.
-- +goose StatementBegin
CREATE OR REPLACE FUNCTION audit_partition_ensure(p_parent regclass, p_from timestamptz, p_through timestamptz)
RETURNS integer
LANGUAGE plpgsql
SET search_path = pg_catalog, public, pg_temp
SET TimeZone = 'UTC'
AS $f$
DECLARE
    lo timestamptz := date_trunc('month', p_from);
    hi timestamptz;
    name text;
    existing regclass;
    def regclass;
    created integer := 0;
BEGIN
    SELECT NULLIF(partdefid, 0)::regclass INTO def FROM pg_partitioned_table WHERE partrelid = p_parent;
    WHILE lo <= p_through LOOP
        hi := lo + interval '1 month';
        name := 'audit_events_p' || to_char(lo, 'YYYYMM');
        existing := to_regclass('public.' || quote_ident(name));
        IF existing IS NOT NULL THEN
            IF NOT EXISTS (SELECT 1 FROM pg_inherits WHERE inhrelid = existing AND inhparent = p_parent) THEN
                RAISE EXCEPTION '% exists but is not a partition of %', name, p_parent
                    USING HINT = 'Attach it, or drop or rename it if it is not wanted, so the month can be created.';
            END IF;
        ELSE
            EXECUTE format('CREATE TABLE public.%I (LIKE %s INCLUDING DEFAULTS INCLUDING CONSTRAINTS INCLUDING STORAGE)',
                name, p_parent);
            EXECUTE format('ALTER TABLE public.%I ADD CONSTRAINT %I CHECK (ts >= %L AND ts < %L)',
                name, name || '_bound', lo, hi);
            IF def IS NOT NULL THEN
                EXECUTE format('WITH moved AS (DELETE FROM %s WHERE ts >= $1 AND ts < $2 RETURNING *) '
                    'INSERT INTO public.%I OVERRIDING SYSTEM VALUE SELECT * FROM moved', def, name) USING lo, hi;
            END IF;
            EXECUTE format('REVOKE ALL ON public.%I FROM PUBLIC, supermcp_app', name);
            EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', name);
            EXECUTE format('ALTER TABLE %s ATTACH PARTITION public.%I FOR VALUES FROM (%L) TO (%L)',
                p_parent, name, lo, hi);
            EXECUTE format('ALTER TABLE public.%I DROP CONSTRAINT %I', name, name || '_bound');
            created := created + 1;
        END IF;
        lo := hi;
    END LOOP;
    RETURN created;
END
$f$;
-- +goose StatementEnd

-- audit_events_cut removes every event at or below p_cut_seq, the
-- retention cut Reader.Cut has chosen and anchored in the same
-- transaction. A partition whose month ended before p_before and that
-- holds nothing above the cut is dropped whole; the rest lose their rows
-- at or below the cut one by one. What is removed is the same prefix of the
-- chain either way, so the anchor bridges it the same way. It returns how
-- many events went and which partitions.
--
-- Everything that reads a whole month (deciding what goes, counting it)
-- and the row-by-row deletes happen first, under the locks any read or
-- delete takes, so appends and reads carry on meanwhile. Only then is
-- ACCESS EXCLUSIVE taken on audit_events to detach and drop the months,
-- after the chain lock the writer appends under, so appends wait on that
-- rather than queue behind the table lock; both give up after
-- p_lock_timeout. Holding them, it checks again with two index probes that
-- nothing was written above the cut into a month being dropped and that no
-- row at or below the cut was put under legal hold since Reader.Cut chose
-- it, and refuses if either happened. A refusal, or a reader holding the
-- table past the timeout, rolls the whole cut back for the next sweep.
--
-- A row put under legal hold after Reader.Cut chose the cut is not deleted
-- either (NOT legal_hold), so the check at the end finds it wherever it is.
-- +goose StatementBegin
CREATE OR REPLACE FUNCTION audit_events_cut(p_cut_seq bigint, p_before timestamptz, p_chain_lock bigint, p_lock_timeout text)
RETURNS TABLE (deleted bigint, dropped text[])
LANGUAGE plpgsql
SET search_path = pg_catalog, public, pg_temp
AS $f$
DECLARE
    part record;
    whole regclass[] := '{}';
    rest regclass[] := '{}';
    p regclass;
    above boolean;
    n bigint;
BEGIN
    deleted := 0;
    dropped := '{}';
    FOR part IN SELECT * FROM public.audit_partition_bounds('public.audit_events'::regclass) LOOP
        IF part.upper_bound IS NOT NULL AND part.upper_bound <= p_before THEN
            EXECUTE format('SELECT EXISTS (SELECT 1 FROM %s WHERE seq > $1)', part.partition) INTO above USING p_cut_seq;
            IF NOT above THEN
                -- Every row here is at or below the cut and new rows take
                -- higher numbers, so the count stays true until the drop.
                EXECUTE format('SELECT count(*) FROM %s', part.partition) INTO n;
                deleted := deleted + n;
                whole := whole || part.partition;
                CONTINUE;
            END IF;
        END IF;
        rest := rest || part.partition;
    END LOOP;

    FOREACH p IN ARRAY rest LOOP
        EXECUTE format('DELETE FROM %s WHERE seq <= $1 AND NOT legal_hold', p) USING p_cut_seq;
        GET DIAGNOSTICS n = ROW_COUNT;
        deleted := deleted + n;
    END LOOP;

    IF cardinality(whole) > 0 THEN
        PERFORM set_config('lock_timeout', p_lock_timeout, true);
        PERFORM pg_advisory_xact_lock(p_chain_lock);
        LOCK TABLE public.audit_events IN ACCESS EXCLUSIVE MODE;
        FOREACH p IN ARRAY whole LOOP
            EXECUTE format('SELECT EXISTS (SELECT 1 FROM %s WHERE seq > $1)', p) INTO above USING p_cut_seq;
            IF above THEN
                RAISE EXCEPTION 'an event above the retention cut at % was written into % while the cut ran', p_cut_seq, p
                    USING HINT = 'Nothing was cut; the next sweep chooses again.';
            END IF;
        END LOOP;
    END IF;
    IF EXISTS (SELECT 1 FROM public.audit_events WHERE legal_hold AND seq <= p_cut_seq) THEN
        RAISE EXCEPTION 'an event at or below the retention cut at % was put under legal hold while the cut ran', p_cut_seq
            USING HINT = 'Nothing was cut; the next sweep stops below the hold.';
    END IF;

    FOREACH p IN ARRAY whole LOOP
        dropped := dropped || p::text;
        EXECUTE format('ALTER TABLE public.audit_events DETACH PARTITION %s', p);
        EXECUTE format('DROP TABLE %s', p);
    END LOOP;
    RETURN NEXT;
END
$f$;
-- +goose StatementEnd

REVOKE ALL ON FUNCTION audit_partition_bounds(regclass) FROM PUBLIC;
REVOKE ALL ON FUNCTION audit_partition_ensure(regclass, timestamptz, timestamptz) FROM PUBLIC;
REVOKE ALL ON FUNCTION audit_events_cut(bigint, timestamptz, bigint, text) FROM PUBLIC;

-- The guard described above. It is only for this migration and is dropped
-- at the end.
-- +goose StatementBegin
CREATE OR REPLACE FUNCTION audit_events_migration_guard()
RETURNS void
LANGUAGE plpgsql
SET search_path = pg_catalog, public, pg_temp
AS $f$
DECLARE
    others text;
BEGIN
    IF NOT EXISTS (SELECT 1 FROM public.audit_events) THEN
        RETURN;
    END IF;
    SELECT string_agg(format('pid %s (role %s, application %s, %s)', a.pid, a.usename,
               COALESCE(NULLIF(a.application_name, ''), 'unnamed'), a.state), '; ' ORDER BY a.pid)
    INTO others
    FROM pg_stat_activity a
    WHERE a.datname = current_database()
      AND a.pid <> pg_backend_pid()
      AND a.backend_type = 'client backend'
      AND a.application_name <> 'supermcp-migrate'
      AND (pg_has_role(a.usesysid, 'supermcp_app', 'MEMBER') OR a.query ILIKE 'listen%');
    IF others IS NOT NULL THEN
        RAISE EXCEPTION 'audit_events cannot be copied while the application is connected to this database: %', others
            USING HINT = 'Stop every replica (kubectl scale deployment/<release> --replicas=0) and close other sessions '
                'in this database, then run the migration again; it continues where it stopped. '
                'docs/UPGRADING.md, migration 00033.';
    END IF;
END
$f$;
-- +goose StatementEnd

-- 1. The partitioned copy, its partitions, and where the copy has got to.
-- Nothing here runs once the swap has happened, so a rerun after it is a
-- no-op.
-- +goose StatementBegin
DO $new$
DECLARE
    oldest timestamptz;
BEGIN
    IF (SELECT relkind FROM pg_class WHERE oid = 'public.audit_events'::regclass) = 'p' THEN
        RETURN;
    END IF;
    -- Left by an earlier upgrade that was then migrated down. The swap
    -- would need its name, and it may be the only copy of something.
    IF to_regclass('public.audit_events_old') IS NOT NULL THEN
        RAISE EXCEPTION 'audit_events_old is still here from an earlier upgrade'
            USING HINT = 'Drop it, or rename it if you want to keep it, and run the migration again. docs/UPGRADING.md, migration 00033.';
    END IF;
    IF to_regclass('public.audit_events_new') IS NULL THEN
        CREATE TABLE audit_events_new (
            seq             bigint GENERATED ALWAYS AS IDENTITY,
            id              uuid NOT NULL,
            ts              timestamptz NOT NULL,
            organization_id text,
            category        text NOT NULL,
            action          text NOT NULL,
            outcome         text NOT NULL,
            actor_kind      text NOT NULL,
            actor_id        text,
            actor_display   text NOT NULL DEFAULT '',
            on_behalf_of    text,
            target_kind     text,
            target_id       text,
            target_display  text NOT NULL DEFAULT '',
            request_id      text,
            session_id      text,
            ip              inet,
            user_agent      text,
            diff            json,
            payload         json,
            meta            json,
            prev_hash       bytea NOT NULL,
            hash            bytea NOT NULL,
            legal_hold      boolean NOT NULL DEFAULT false,
            content_hash    bytea NOT NULL,
            scrubbed_at     timestamptz,
            CONSTRAINT audit_events_new_outcome_check CHECK (outcome IN ('success', 'failure', 'denied', 'pending'))
        ) PARTITION BY RANGE (ts);

        ALTER TABLE audit_events_new ENABLE ROW LEVEL SECURITY;
        ALTER TABLE audit_events_new FORCE ROW LEVEL SECURITY;
        CREATE POLICY org_isolation ON audit_events_new FOR SELECT USING (organization_id = current_org());
        -- The default privileges from 00002 granted the application role
        -- everything; it gets back exactly what it had on audit_events.
        REVOKE ALL ON audit_events_new FROM PUBLIC, supermcp_app;
        GRANT SELECT ON audit_events_new TO supermcp_app;
        GRANT UPDATE (diff, payload, scrubbed_at) ON audit_events_new TO supermcp_app;

        CREATE TABLE audit_events_default PARTITION OF audit_events_new DEFAULT;
        REVOKE ALL ON audit_events_default FROM PUBLIC, supermcp_app;
        ALTER TABLE audit_events_default ENABLE ROW LEVEL SECURITY;
    END IF;

    IF to_regclass('public.audit_events_copy_progress') IS NULL THEN
        CREATE TABLE audit_events_copy_progress (copied_through bigint NOT NULL);
        INSERT INTO audit_events_copy_progress VALUES (0);
        REVOKE ALL ON audit_events_copy_progress FROM PUBLIC, supermcp_app;
    END IF;

    -- One read of ts over the whole table. The oldest by seq is not
    -- necessarily the oldest by time, and a month missed here would put
    -- its rows in the default partition.
    SELECT min(ts) INTO oldest FROM audit_events;
    PERFORM audit_partition_ensure('public.audit_events_new'::regclass,
        LEAST(COALESCE(oldest, now()), now()), now() + interval '3 months');
END
$new$;
-- +goose StatementEnd

-- 2. The copy. A procedure, because it commits after each batch: a failure
-- loses one batch of work, not all of it, and a rerun continues from the
-- progress row. OVERRIDING SYSTEM VALUE keeps every seq as it was; the
-- chain is keyed on it.
-- +goose StatementBegin
-- No SET search_path on it: a procedure with a SET clause may not commit.
CREATE OR REPLACE PROCEDURE audit_events_copy_batches(p_batch integer)
LANGUAGE plpgsql
AS $p$
DECLARE
    done bigint;
    upto bigint;
    batches integer := 0;
    stop_after integer := NULLIF(current_setting('supermcp.audit_copy_batches', true), '')::integer;
BEGIN
    IF to_regclass('public.audit_events_copy_progress') IS NULL THEN
        RETURN;
    END IF;
    PERFORM public.audit_events_migration_guard();
    LOOP
        SELECT copied_through INTO done FROM public.audit_events_copy_progress;
        SELECT max(seq) INTO upto FROM (
            SELECT seq FROM public.audit_events WHERE seq > done ORDER BY seq LIMIT p_batch) s;
        EXIT WHEN upto IS NULL;
        IF batches = stop_after THEN
            RAISE EXCEPTION 'stopped after % batches, as supermcp.audit_copy_batches asked; run again to continue', batches;
        END IF;
        INSERT INTO public.audit_events_new (seq, id, ts, organization_id, category, action, outcome, actor_kind,
            actor_id, actor_display, on_behalf_of, target_kind, target_id, target_display, request_id,
            session_id, ip, user_agent, diff, payload, meta, prev_hash, hash, legal_hold, content_hash, scrubbed_at)
        OVERRIDING SYSTEM VALUE
        SELECT seq, id, ts, organization_id, category, action, outcome, actor_kind,
            actor_id, actor_display, on_behalf_of, target_kind, target_id, target_display, request_id,
            session_id, ip, user_agent, diff, payload, meta, prev_hash, hash, legal_hold, content_hash, scrubbed_at
        FROM public.audit_events WHERE seq > done AND seq <= upto;
        UPDATE public.audit_events_copy_progress SET copied_through = upto;
        COMMIT;
        batches := batches + 1;
    END LOOP;
END
$p$;
-- +goose StatementEnd

CALL audit_events_copy_batches(COALESCE(NULLIF(current_setting('supermcp.audit_copy_batch', true), '')::integer, 50000));

-- 3. Keys and indexes, on the parent, so every partition has them and
-- every partition created later gets them. Not CONCURRENTLY: nothing
-- reads or writes audit_events_new yet. Two transactions, the btrees and
-- then the search index, which takes most of the time; a rerun skips what
-- was built, and after the swap skips both. maintenance_work_mem is raised
-- to 256MB for them unless the role already has more.
-- +goose StatementBegin
DO $keys$
BEGIN
    IF to_regclass('public.audit_events_new') IS NULL THEN
        RETURN;
    END IF;
    IF pg_size_bytes(current_setting('maintenance_work_mem')) < pg_size_bytes('256MB') THEN
        PERFORM set_config('maintenance_work_mem', '256MB', true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'audit_events_new_pkey') THEN
        ALTER TABLE audit_events_new ADD CONSTRAINT audit_events_new_pkey PRIMARY KEY (seq, ts);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'audit_events_new_id_key') THEN
        ALTER TABLE audit_events_new ADD CONSTRAINT audit_events_new_id_key UNIQUE (id, ts);
    END IF;
    CREATE INDEX IF NOT EXISTS audit_events_new_org_time_idx ON audit_events_new (organization_id, ts DESC);
    CREATE INDEX IF NOT EXISTS audit_events_new_action_idx ON audit_events_new (organization_id, category, action, ts DESC);
    CREATE INDEX IF NOT EXISTS audit_events_new_actor_idx ON audit_events_new (actor_id, ts DESC);
    CREATE INDEX IF NOT EXISTS audit_events_new_target_idx ON audit_events_new (target_kind, target_id, ts DESC);
    CREATE INDEX IF NOT EXISTS audit_events_new_org_seq_idx ON audit_events_new (organization_id, seq);
    CREATE INDEX IF NOT EXISTS audit_events_new_legal_hold_idx ON audit_events_new (seq) WHERE legal_hold;
END
$keys$;
-- +goose StatementEnd

-- +goose StatementBegin
DO $search$
BEGIN
    IF to_regclass('public.audit_events_new') IS NULL THEN
        RETURN;
    END IF;
    IF pg_size_bytes(current_setting('maintenance_work_mem')) < pg_size_bytes('256MB') THEN
        PERFORM set_config('maintenance_work_mem', '256MB', true);
    END IF;
    CREATE INDEX IF NOT EXISTS audit_events_new_search_idx ON audit_events_new
        USING gin (audit_search_document(action, actor_id, actor_display, target_kind, target_id, target_display, meta));
END
$search$;
-- +goose StatementEnd

-- 4. The swap, in one transaction. ACCESS EXCLUSIVE on the old table,
-- waited for at most 30 seconds, for as long as the tail copy, bringing
-- the copied rows up to date, and the renames take.
-- +goose StatementBegin
DO $swap$
DECLARE
    done bigint;
    oldseq text;
    last bigint;
    called boolean;
    changed bigint;
BEGIN
    IF (SELECT relkind FROM pg_class WHERE oid = 'public.audit_events'::regclass) = 'p' THEN
        RETURN;
    END IF;
    PERFORM audit_events_migration_guard();
    PERFORM set_config('lock_timeout', '30s', true);
    LOCK TABLE audit_events IN ACCESS EXCLUSIVE MODE;
    PERFORM set_config('lock_timeout', '0', true);

    SELECT copied_through INTO done FROM audit_events_copy_progress;
    INSERT INTO audit_events_new (seq, id, ts, organization_id, category, action, outcome, actor_kind,
        actor_id, actor_display, on_behalf_of, target_kind, target_id, target_display, request_id,
        session_id, ip, user_agent, diff, payload, meta, prev_hash, hash, legal_hold, content_hash, scrubbed_at)
    OVERRIDING SYSTEM VALUE
    SELECT seq, id, ts, organization_id, category, action, outcome, actor_kind,
        actor_id, actor_display, on_behalf_of, target_kind, target_id, target_display, request_id,
        session_id, ip, user_agent, diff, payload, meta, prev_hash, hash, legal_hold, content_hash, scrubbed_at
    FROM audit_events WHERE seq > done;

    -- What changed in the old table after its rows were copied: the only
    -- columns anything updates (a scrub, a legal hold, a pseudonymised
    -- name), and rows a cut removed. json has no equality, so its text is
    -- compared; it is stored as given.
    UPDATE audit_events_new n
    SET diff = o.diff, payload = o.payload, scrubbed_at = o.scrubbed_at, legal_hold = o.legal_hold,
        actor_display = o.actor_display, target_display = o.target_display
    FROM audit_events o
    WHERE o.seq = n.seq AND o.ts = n.ts AND n.seq <= done
      AND (o.diff::text IS DISTINCT FROM n.diff::text OR o.payload::text IS DISTINCT FROM n.payload::text
           OR o.scrubbed_at IS DISTINCT FROM n.scrubbed_at OR o.legal_hold <> n.legal_hold
           OR o.actor_display <> n.actor_display OR o.target_display <> n.target_display);
    GET DIAGNOSTICS changed = ROW_COUNT;
    IF changed > 0 THEN
        RAISE NOTICE '% copied audit events changed during the copy and were brought up to date', changed;
    END IF;
    DELETE FROM audit_events_new n
    WHERE n.seq <= done AND NOT EXISTS (SELECT 1 FROM audit_events o WHERE o.seq = n.seq);
    GET DIAGNOSTICS changed = ROW_COUNT;
    IF changed > 0 THEN
        RAISE NOTICE '% copied audit events were removed from the old table during the copy and from the copy too', changed;
    END IF;

    -- The next event takes the number the old table would have given it.
    oldseq := pg_get_serial_sequence('public.audit_events', 'seq');
    EXECUTE format('SELECT last_value, is_called FROM %s', oldseq) INTO last, called;
    PERFORM setval(pg_get_serial_sequence('public.audit_events_new', 'seq'), last, called);

    ALTER TABLE audit_events RENAME TO audit_events_old;
    ALTER TABLE audit_events_old RENAME CONSTRAINT audit_events_pkey TO audit_events_old_pkey;
    ALTER TABLE audit_events_old RENAME CONSTRAINT audit_events_id_key TO audit_events_old_id_key;
    ALTER TABLE audit_events_old RENAME CONSTRAINT audit_events_outcome_check TO audit_events_old_outcome_check;
    ALTER INDEX audit_events_org_time_idx RENAME TO audit_events_old_org_time_idx;
    ALTER INDEX audit_events_action_idx RENAME TO audit_events_old_action_idx;
    ALTER INDEX audit_events_actor_idx RENAME TO audit_events_old_actor_idx;
    ALTER INDEX audit_events_target_idx RENAME TO audit_events_old_target_idx;
    ALTER INDEX IF EXISTS audit_events_org_seq_idx RENAME TO audit_events_old_org_seq_idx;
    ALTER INDEX IF EXISTS audit_events_search_idx RENAME TO audit_events_old_search_idx;
    ALTER SEQUENCE audit_events_seq_seq RENAME TO audit_events_old_seq_seq;
    -- The copy is the record now. The old table is kept for the operator
    -- to compare against and drop, not for the application to read.
    REVOKE ALL ON audit_events_old FROM PUBLIC, supermcp_app;

    ALTER TABLE audit_events_new RENAME TO audit_events;
    ALTER TABLE audit_events RENAME CONSTRAINT audit_events_new_pkey TO audit_events_pkey;
    ALTER TABLE audit_events RENAME CONSTRAINT audit_events_new_id_key TO audit_events_id_key;
    ALTER TABLE audit_events RENAME CONSTRAINT audit_events_new_outcome_check TO audit_events_outcome_check;
    ALTER INDEX audit_events_new_org_time_idx RENAME TO audit_events_org_time_idx;
    ALTER INDEX audit_events_new_action_idx RENAME TO audit_events_action_idx;
    ALTER INDEX audit_events_new_actor_idx RENAME TO audit_events_actor_idx;
    ALTER INDEX audit_events_new_target_idx RENAME TO audit_events_target_idx;
    ALTER INDEX audit_events_new_org_seq_idx RENAME TO audit_events_org_seq_idx;
    ALTER INDEX audit_events_new_legal_hold_idx RENAME TO audit_events_legal_hold_idx;
    ALTER INDEX audit_events_new_search_idx RENAME TO audit_events_search_idx;
    ALTER SEQUENCE audit_events_new_seq_seq RENAME TO audit_events_seq_seq;

    DROP TABLE audit_events_copy_progress;
    -- A new installation has nothing to compare against.
    IF NOT EXISTS (SELECT 1 FROM audit_events_old) THEN
        DROP TABLE audit_events_old;
    END IF;
END
$swap$;
-- +goose StatementEnd

DROP PROCEDURE IF EXISTS audit_events_copy_batches(integer);
DROP FUNCTION IF EXISTS audit_events_migration_guard();

-- Autovacuum never analyzes a partitioned table itself, only its
-- partitions, and the planner needs the parent's statistics for anything
-- that reads across months. The partition maintenance job analyzes it from
-- here on.
VACUUM (ANALYZE) audit_events;

-- +goose Down

-- Back to one plain table, built from the partitioned one so that what was
-- written, scrubbed, held or cut since the upgrade is what comes back.
-- audit_events_old, if it is still there, is left alone. Like the way up,
-- this wants every replica stopped; it is not resumable, and a failure
-- rolls back to the partitioned table.
-- +goose StatementBegin
DO $down$
DECLARE
    last bigint;
    called boolean;
BEGIN
    IF (SELECT relkind FROM pg_class WHERE oid = 'public.audit_events'::regclass) <> 'p' THEN
        RETURN;
    END IF;
    LOCK TABLE audit_events IN ACCESS EXCLUSIVE MODE;
    CREATE TABLE audit_events_plain (
        seq             bigint GENERATED ALWAYS AS IDENTITY,
        id              uuid NOT NULL,
        ts              timestamptz NOT NULL,
        organization_id text,
        category        text NOT NULL,
        action          text NOT NULL,
        outcome         text NOT NULL,
        actor_kind      text NOT NULL,
        actor_id        text,
        actor_display   text NOT NULL DEFAULT '',
        on_behalf_of    text,
        target_kind     text,
        target_id       text,
        target_display  text NOT NULL DEFAULT '',
        request_id      text,
        session_id      text,
        ip              inet,
        user_agent      text,
        diff            json,
        payload         json,
        meta            json,
        prev_hash       bytea NOT NULL,
        hash            bytea NOT NULL,
        legal_hold      boolean NOT NULL DEFAULT false,
        content_hash    bytea NOT NULL,
        scrubbed_at     timestamptz
    );
    INSERT INTO audit_events_plain OVERRIDING SYSTEM VALUE SELECT * FROM audit_events ORDER BY seq;
    SELECT last_value, is_called INTO last, called FROM audit_events_seq_seq;

    DROP TABLE audit_events;
    ALTER TABLE audit_events_plain RENAME TO audit_events;
    ALTER SEQUENCE audit_events_plain_seq_seq RENAME TO audit_events_seq_seq;
    PERFORM setval('public.audit_events_seq_seq', last, called);
    ALTER TABLE audit_events ADD CONSTRAINT audit_events_pkey PRIMARY KEY (seq);
    ALTER TABLE audit_events ADD CONSTRAINT audit_events_id_key UNIQUE (id);
    ALTER TABLE audit_events ADD CONSTRAINT audit_events_outcome_check
        CHECK (outcome IN ('success', 'failure', 'denied', 'pending'));
    CREATE INDEX audit_events_org_time_idx ON audit_events (organization_id, ts DESC);
    CREATE INDEX audit_events_action_idx ON audit_events (organization_id, category, action, ts DESC);
    CREATE INDEX audit_events_actor_idx ON audit_events (actor_id, ts DESC);
    CREATE INDEX audit_events_target_idx ON audit_events (target_kind, target_id, ts DESC);
    CREATE INDEX audit_events_org_seq_idx ON audit_events (organization_id, seq);
    CREATE INDEX audit_events_search_idx ON audit_events
        USING gin (audit_search_document(action, actor_id, actor_display, target_kind, target_id, target_display, meta));

    ALTER TABLE audit_events ENABLE ROW LEVEL SECURITY;
    ALTER TABLE audit_events FORCE ROW LEVEL SECURITY;
    CREATE POLICY org_isolation ON audit_events FOR SELECT USING (organization_id = current_org());
    REVOKE ALL ON audit_events FROM PUBLIC, supermcp_app;
    GRANT SELECT ON audit_events TO supermcp_app;
    GRANT UPDATE (diff, payload, scrubbed_at) ON audit_events TO supermcp_app;
END
$down$;
-- +goose StatementEnd

DROP PROCEDURE IF EXISTS audit_events_copy_batches(integer);
DROP FUNCTION IF EXISTS audit_events_migration_guard();
DROP FUNCTION IF EXISTS audit_events_cut(bigint, timestamptz, bigint, text);
DROP FUNCTION IF EXISTS audit_partition_ensure(regclass, timestamptz, timestamptz);
DROP FUNCTION IF EXISTS audit_partition_bounds(regclass);
