/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiKeysRouteImport } from './routes/api-keys'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ServersRouteImport } from './routes/servers'
import { Route as StatusRouteImport } from './routes/status'
import { Route as ToolCallsRouteImport } from './routes/tool-calls'
import { Route as CatalogIndexRouteImport } from './routes/catalog.index'
import { Route as CatalogSlugRouteImport } from './routes/catalog.$slug'
import { Route as ConnectorsIndexRouteImport } from './routes/connectors.index'
import { Route as ConnectorsImportRouteImport } from './routes/connectors.import'
import { Route as SettingsAuditRouteImport } from './routes/settings.audit'
import { Route as SettingsDlpRouteImport } from './routes/settings.dlp'
import { Route as SettingsRolesRouteImport } from './routes/settings.roles'
import { Route as SettingsSecurityRouteImport } from './routes/settings.security'
import { Route as SettingsServiceAccountsRouteImport } from './routes/settings.service-accounts'
import { Route as SettingsSsoRouteImport } from './routes/settings.sso'
import { Route as ConnectorsIdHistoryRouteImport } from './routes/connectors.$id.history'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeysRoute = ApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ServersRoute = ServersRouteImport.update({
  id: '/servers',
  path: '/servers',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolCallsRoute = ToolCallsRouteImport.update({
  id: '/tool-calls',
  path: '/tool-calls',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogIndexRoute = CatalogIndexRouteImport.update({
  id: '/catalog/',
  path: '/catalog/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogSlugRoute = CatalogSlugRouteImport.update({
  id: '/catalog/$slug',
  path: '/catalog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectorsIndexRoute = ConnectorsIndexRouteImport.update({
  id: '/connectors/',
  path: '/connectors/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectorsImportRoute = ConnectorsImportRouteImport.update({
  id: '/connectors/import',
  path: '/connectors/import',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAuditRoute = SettingsAuditRouteImport.update({
  id: '/settings/audit',
  path: '/settings/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsDlpRoute = SettingsDlpRouteImport.update({
  id: '/settings/dlp',
  path: '/settings/dlp',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRolesRoute = SettingsRolesRouteImport.update({
  id: '/settings/roles',
  path: '/settings/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSecurityRoute = SettingsSecurityRouteImport.update({
  id: '/settings/security',
  path: '/settings/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsServiceAccountsRoute = SettingsServiceAccountsRouteImport.update({
  id: '/settings/service-accounts',
  path: '/settings/service-accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSsoRoute = SettingsSsoRouteImport.update({
  id: '/settings/sso',
  path: '/settings/sso',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectorsIdHistoryRoute = ConnectorsIdHistoryRouteImport.update({
  id: '/connectors/$id/history',
  path: '/connectors/$id/history',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api-keys': typeof ApiKeysRoute
  '/approvals': typeof ApprovalsRoute
  '/login': typeof LoginRoute
  '/servers': typeof ServersRoute
  '/status': typeof StatusRoute
  '/tool-calls': typeof ToolCallsRoute
  '/catalog/$slug': typeof CatalogSlugRoute
  '/connectors/import': typeof ConnectorsImportRoute
  '/settings/audit': typeof SettingsAuditRoute
  '/settings/dlp': typeof SettingsDlpRoute
  '/settings/roles': typeof SettingsRolesRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings/service-accounts': typeof SettingsServiceAccountsRoute
  '/settings/sso': typeof SettingsSsoRoute
  '/catalog/': typeof CatalogIndexRoute
  '/connectors/': typeof ConnectorsIndexRoute
  '/connectors/$id/history': typeof ConnectorsIdHistoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api-keys': typeof ApiKeysRoute
  '/approvals': typeof ApprovalsRoute
  '/login': typeof LoginRoute
  '/servers': typeof ServersRoute
  '/status': typeof StatusRoute
  '/tool-calls': typeof ToolCallsRoute
  '/catalog/$slug': typeof CatalogSlugRoute
  '/connectors/import': typeof ConnectorsImportRoute
  '/settings/audit': typeof SettingsAuditRoute
  '/settings/dlp': typeof SettingsDlpRoute
  '/settings/roles': typeof SettingsRolesRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings/service-accounts': typeof SettingsServiceAccountsRoute
  '/settings/sso': typeof SettingsSsoRoute
  '/catalog': typeof CatalogIndexRoute
  '/connectors': typeof ConnectorsIndexRoute
  '/connectors/$id/history': typeof ConnectorsIdHistoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api-keys': typeof ApiKeysRoute
  '/approvals': typeof ApprovalsRoute
  '/login': typeof LoginRoute
  '/servers': typeof ServersRoute
  '/status': typeof StatusRoute
  '/tool-calls': typeof ToolCallsRoute
  '/catalog/$slug': typeof CatalogSlugRoute
  '/connectors/import': typeof ConnectorsImportRoute
  '/settings/audit': typeof SettingsAuditRoute
  '/settings/dlp': typeof SettingsDlpRoute
  '/settings/roles': typeof SettingsRolesRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/settings/service-accounts': typeof SettingsServiceAccountsRoute
  '/settings/sso': typeof SettingsSsoRoute
  '/catalog/': typeof CatalogIndexRoute
  '/connectors/': typeof ConnectorsIndexRoute
  '/connectors/$id/history': typeof ConnectorsIdHistoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api-keys'
    | '/approvals'
    | '/login'
    | '/servers'
    | '/status'
    | '/tool-calls'
    | '/catalog/$slug'
    | '/connectors/import'
    | '/settings/audit'
    | '/settings/dlp'
    | '/settings/roles'
    | '/settings/security'
    | '/settings/service-accounts'
    | '/settings/sso'
    | '/catalog/'
    | '/connectors/'
    | '/connectors/$id/history'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api-keys'
    | '/approvals'
    | '/login'
    | '/servers'
    | '/status'
    | '/tool-calls'
    | '/catalog/$slug'
    | '/connectors/import'
    | '/settings/audit'
    | '/settings/dlp'
    | '/settings/roles'
    | '/settings/security'
    | '/settings/service-accounts'
    | '/settings/sso'
    | '/catalog'
    | '/connectors'
    | '/connectors/$id/history'
  id:
    | '__root__'
    | '/'
    | '/api-keys'
    | '/approvals'
    | '/login'
    | '/servers'
    | '/status'
    | '/tool-calls'
    | '/catalog/$slug'
    | '/connectors/import'
    | '/settings/audit'
    | '/settings/dlp'
    | '/settings/roles'
    | '/settings/security'
    | '/settings/service-accounts'
    | '/settings/sso'
    | '/catalog/'
    | '/connectors/'
    | '/connectors/$id/history'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiKeysRoute: typeof ApiKeysRoute
  ApprovalsRoute: typeof ApprovalsRoute
  LoginRoute: typeof LoginRoute
  ServersRoute: typeof ServersRoute
  StatusRoute: typeof StatusRoute
  ToolCallsRoute: typeof ToolCallsRoute
  CatalogSlugRoute: typeof CatalogSlugRoute
  ConnectorsImportRoute: typeof ConnectorsImportRoute
  SettingsAuditRoute: typeof SettingsAuditRoute
  SettingsDlpRoute: typeof SettingsDlpRoute
  SettingsRolesRoute: typeof SettingsRolesRoute
  SettingsSecurityRoute: typeof SettingsSecurityRoute
  SettingsServiceAccountsRoute: typeof SettingsServiceAccountsRoute
  SettingsSsoRoute: typeof SettingsSsoRoute
  CatalogIndexRoute: typeof CatalogIndexRoute
  ConnectorsIndexRoute: typeof ConnectorsIndexRoute
  ConnectorsIdHistoryRoute: typeof ConnectorsIdHistoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-keys': {
      id: '/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof ApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servers': {
      id: '/servers'
      path: '/servers'
      fullPath: '/servers'
      preLoaderRoute: typeof ServersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tool-calls': {
      id: '/tool-calls'
      path: '/tool-calls'
      fullPath: '/tool-calls'
      preLoaderRoute: typeof ToolCallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/': {
      id: '/catalog/'
      path: '/catalog'
      fullPath: '/catalog/'
      preLoaderRoute: typeof CatalogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/$slug': {
      id: '/catalog/$slug'
      path: '/catalog/$slug'
      fullPath: '/catalog/$slug'
      preLoaderRoute: typeof CatalogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connectors/': {
      id: '/connectors/'
      path: '/connectors'
      fullPath: '/connectors/'
      preLoaderRoute: typeof ConnectorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connectors/import': {
      id: '/connectors/import'
      path: '/connectors/import'
      fullPath: '/connectors/import'
      preLoaderRoute: typeof ConnectorsImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/audit': {
      id: '/settings/audit'
      path: '/settings/audit'
      fullPath: '/settings/audit'
      preLoaderRoute: typeof SettingsAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/dlp': {
      id: '/settings/dlp'
      path: '/settings/dlp'
      fullPath: '/settings/dlp'
      preLoaderRoute: typeof SettingsDlpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/roles': {
      id: '/settings/roles'
      path: '/settings/roles'
      fullPath: '/settings/roles'
      preLoaderRoute: typeof SettingsRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/security': {
      id: '/settings/security'
      path: '/settings/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof SettingsSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/service-accounts': {
      id: '/settings/service-accounts'
      path: '/settings/service-accounts'
      fullPath: '/settings/service-accounts'
      preLoaderRoute: typeof SettingsServiceAccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/sso': {
      id: '/settings/sso'
      path: '/settings/sso'
      fullPath: '/settings/sso'
      preLoaderRoute: typeof SettingsSsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connectors/$id/history': {
      id: '/connectors/$id/history'
      path: '/connectors/$id/history'
      fullPath: '/connectors/$id/history'
      preLoaderRoute: typeof ConnectorsIdHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiKeysRoute: ApiKeysRoute,
  ApprovalsRoute: ApprovalsRoute,
  LoginRoute: LoginRoute,
  ServersRoute: ServersRoute,
  StatusRoute: StatusRoute,
  ToolCallsRoute: ToolCallsRoute,
  CatalogSlugRoute: CatalogSlugRoute,
  ConnectorsImportRoute: ConnectorsImportRoute,
  SettingsAuditRoute: SettingsAuditRoute,
  SettingsDlpRoute: SettingsDlpRoute,
  SettingsRolesRoute: SettingsRolesRoute,
  SettingsSecurityRoute: SettingsSecurityRoute,
  SettingsServiceAccountsRoute: SettingsServiceAccountsRoute,
  SettingsSsoRoute: SettingsSsoRoute,
  CatalogIndexRoute: CatalogIndexRoute,
  ConnectorsIndexRoute: ConnectorsIndexRoute,
  ConnectorsIdHistoryRoute: ConnectorsIdHistoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
