/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'
import { Route as AppApiKeysRouteImport } from './routes/_app.api-keys'
import { Route as AppApprovalsRouteImport } from './routes/_app.approvals'
import { Route as AppReauthRouteImport } from './routes/_app.reauth'
import { Route as AppServersRouteImport } from './routes/_app.servers'
import { Route as AppStatusRouteImport } from './routes/_app.status'
import { Route as AppToolCallsRouteImport } from './routes/_app.tool-calls'
import { Route as PublicLoginRouteImport } from './routes/_public.login'
import { Route as AppCatalogIndexRouteImport } from './routes/_app.catalog.index'
import { Route as AppCatalogSlugRouteImport } from './routes/_app.catalog.$slug'
import { Route as AppConnectorsIndexRouteImport } from './routes/_app.connectors.index'
import { Route as AppConnectorsImportRouteImport } from './routes/_app.connectors.import'
import { Route as AppSettingsAuditRouteImport } from './routes/_app.settings.audit'
import { Route as AppSettingsDlpRouteImport } from './routes/_app.settings.dlp'
import { Route as AppSettingsMembersRouteImport } from './routes/_app.settings.members'
import { Route as AppSettingsRolesRouteImport } from './routes/_app.settings.roles'
import { Route as AppSettingsSecurityRouteImport } from './routes/_app.settings.security'
import { Route as AppSettingsServiceAccountsRouteImport } from './routes/_app.settings.service-accounts'
import { Route as AppSettingsSsoRouteImport } from './routes/_app.settings.sso'
import { Route as PublicInviteTokenRouteImport } from './routes/_public.invite.$token'
import { Route as AppConnectorsIdHistoryRouteImport } from './routes/_app.connectors.$id.history'
import { Route as AppConnectorsIdToolsIndexRouteImport } from './routes/_app.connectors.$id.tools.index'
import { Route as AppConnectorsIdToolsNewRouteImport } from './routes/_app.connectors.$id.tools.new'
import { Route as AppConnectorsIdToolsToolIdIndexRouteImport } from './routes/_app.connectors.$id.tools.$toolId.index'
import { Route as AppConnectorsIdToolsToolIdHistoryRouteImport } from './routes/_app.connectors.$id.tools.$toolId.history'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppApiKeysRoute = AppApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AppRoute,
} as any)
const AppApprovalsRoute = AppApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => AppRoute,
} as any)
const AppReauthRoute = AppReauthRouteImport.update({
  id: '/reauth',
  path: '/reauth',
  getParentRoute: () => AppRoute,
} as any)
const AppServersRoute = AppServersRouteImport.update({
  id: '/servers',
  path: '/servers',
  getParentRoute: () => AppRoute,
} as any)
const AppStatusRoute = AppStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => AppRoute,
} as any)
const AppToolCallsRoute = AppToolCallsRouteImport.update({
  id: '/tool-calls',
  path: '/tool-calls',
  getParentRoute: () => AppRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const AppCatalogIndexRoute = AppCatalogIndexRouteImport.update({
  id: '/catalog/',
  path: '/catalog/',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogSlugRoute = AppCatalogSlugRouteImport.update({
  id: '/catalog/$slug',
  path: '/catalog/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectorsIndexRoute = AppConnectorsIndexRouteImport.update({
  id: '/connectors/',
  path: '/connectors/',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectorsImportRoute = AppConnectorsImportRouteImport.update({
  id: '/connectors/import',
  path: '/connectors/import',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsAuditRoute = AppSettingsAuditRouteImport.update({
  id: '/settings/audit',
  path: '/settings/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsDlpRoute = AppSettingsDlpRouteImport.update({
  id: '/settings/dlp',
  path: '/settings/dlp',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsMembersRoute = AppSettingsMembersRouteImport.update({
  id: '/settings/members',
  path: '/settings/members',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRolesRoute = AppSettingsRolesRouteImport.update({
  id: '/settings/roles',
  path: '/settings/roles',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsSecurityRoute = AppSettingsSecurityRouteImport.update({
  id: '/settings/security',
  path: '/settings/security',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsServiceAccountsRoute =
  AppSettingsServiceAccountsRouteImport.update({
    id: '/settings/service-accounts',
    path: '/settings/service-accounts',
    getParentRoute: () => AppRoute,
  } as any)
const AppSettingsSsoRoute = AppSettingsSsoRouteImport.update({
  id: '/settings/sso',
  path: '/settings/sso',
  getParentRoute: () => AppRoute,
} as any)
const PublicInviteTokenRoute = PublicInviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => PublicRoute,
} as any)
const AppConnectorsIdHistoryRoute = AppConnectorsIdHistoryRouteImport.update({
  id: '/connectors/$id/history',
  path: '/connectors/$id/history',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectorsIdToolsIndexRoute =
  AppConnectorsIdToolsIndexRouteImport.update({
    id: '/connectors/$id/tools/',
    path: '/connectors/$id/tools/',
    getParentRoute: () => AppRoute,
  } as any)
const AppConnectorsIdToolsNewRoute = AppConnectorsIdToolsNewRouteImport.update({
  id: '/connectors/$id/tools/new',
  path: '/connectors/$id/tools/new',
  getParentRoute: () => AppRoute,
} as any)
const AppConnectorsIdToolsToolIdIndexRoute =
  AppConnectorsIdToolsToolIdIndexRouteImport.update({
    id: '/connectors/$id/tools/$toolId/',
    path: '/connectors/$id/tools/$toolId/',
    getParentRoute: () => AppRoute,
  } as any)
const AppConnectorsIdToolsToolIdHistoryRoute =
  AppConnectorsIdToolsToolIdHistoryRouteImport.update({
    id: '/connectors/$id/tools/$toolId/history',
    path: '/connectors/$id/tools/$toolId/history',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/analytics': typeof AppAnalyticsRoute
  '/api-keys': typeof AppApiKeysRoute
  '/approvals': typeof AppApprovalsRoute
  '/reauth': typeof AppReauthRoute
  '/servers': typeof AppServersRoute
  '/status': typeof AppStatusRoute
  '/tool-calls': typeof AppToolCallsRoute
  '/login': typeof PublicLoginRoute
  '/catalog/$slug': typeof AppCatalogSlugRoute
  '/connectors/import': typeof AppConnectorsImportRoute
  '/settings/audit': typeof AppSettingsAuditRoute
  '/settings/dlp': typeof AppSettingsDlpRoute
  '/settings/members': typeof AppSettingsMembersRoute
  '/settings/roles': typeof AppSettingsRolesRoute
  '/settings/security': typeof AppSettingsSecurityRoute
  '/settings/service-accounts': typeof AppSettingsServiceAccountsRoute
  '/settings/sso': typeof AppSettingsSsoRoute
  '/invite/$token': typeof PublicInviteTokenRoute
  '/catalog/': typeof AppCatalogIndexRoute
  '/connectors/': typeof AppConnectorsIndexRoute
  '/connectors/$id/history': typeof AppConnectorsIdHistoryRoute
  '/connectors/$id/tools/new': typeof AppConnectorsIdToolsNewRoute
  '/connectors/$id/tools/': typeof AppConnectorsIdToolsIndexRoute
  '/connectors/$id/tools/$toolId/history': typeof AppConnectorsIdToolsToolIdHistoryRoute
  '/connectors/$id/tools/$toolId/': typeof AppConnectorsIdToolsToolIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/analytics': typeof AppAnalyticsRoute
  '/api-keys': typeof AppApiKeysRoute
  '/approvals': typeof AppApprovalsRoute
  '/reauth': typeof AppReauthRoute
  '/servers': typeof AppServersRoute
  '/status': typeof AppStatusRoute
  '/tool-calls': typeof AppToolCallsRoute
  '/login': typeof PublicLoginRoute
  '/catalog/$slug': typeof AppCatalogSlugRoute
  '/connectors/import': typeof AppConnectorsImportRoute
  '/settings/audit': typeof AppSettingsAuditRoute
  '/settings/dlp': typeof AppSettingsDlpRoute
  '/settings/members': typeof AppSettingsMembersRoute
  '/settings/roles': typeof AppSettingsRolesRoute
  '/settings/security': typeof AppSettingsSecurityRoute
  '/settings/service-accounts': typeof AppSettingsServiceAccountsRoute
  '/settings/sso': typeof AppSettingsSsoRoute
  '/invite/$token': typeof PublicInviteTokenRoute
  '/catalog': typeof AppCatalogIndexRoute
  '/connectors': typeof AppConnectorsIndexRoute
  '/connectors/$id/history': typeof AppConnectorsIdHistoryRoute
  '/connectors/$id/tools/new': typeof AppConnectorsIdToolsNewRoute
  '/connectors/$id/tools': typeof AppConnectorsIdToolsIndexRoute
  '/connectors/$id/tools/$toolId/history': typeof AppConnectorsIdToolsToolIdHistoryRoute
  '/connectors/$id/tools/$toolId': typeof AppConnectorsIdToolsToolIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/api-keys': typeof AppApiKeysRoute
  '/_app/approvals': typeof AppApprovalsRoute
  '/_app/reauth': typeof AppReauthRoute
  '/_app/servers': typeof AppServersRoute
  '/_app/status': typeof AppStatusRoute
  '/_app/tool-calls': typeof AppToolCallsRoute
  '/_public/login': typeof PublicLoginRoute
  '/_app/': typeof AppIndexRoute
  '/_app/catalog/$slug': typeof AppCatalogSlugRoute
  '/_app/connectors/import': typeof AppConnectorsImportRoute
  '/_app/settings/audit': typeof AppSettingsAuditRoute
  '/_app/settings/dlp': typeof AppSettingsDlpRoute
  '/_app/settings/members': typeof AppSettingsMembersRoute
  '/_app/settings/roles': typeof AppSettingsRolesRoute
  '/_app/settings/security': typeof AppSettingsSecurityRoute
  '/_app/settings/service-accounts': typeof AppSettingsServiceAccountsRoute
  '/_app/settings/sso': typeof AppSettingsSsoRoute
  '/_public/invite/$token': typeof PublicInviteTokenRoute
  '/_app/catalog/': typeof AppCatalogIndexRoute
  '/_app/connectors/': typeof AppConnectorsIndexRoute
  '/_app/connectors/$id/history': typeof AppConnectorsIdHistoryRoute
  '/_app/connectors/$id/tools/new': typeof AppConnectorsIdToolsNewRoute
  '/_app/connectors/$id/tools/': typeof AppConnectorsIdToolsIndexRoute
  '/_app/connectors/$id/tools/$toolId/history': typeof AppConnectorsIdToolsToolIdHistoryRoute
  '/_app/connectors/$id/tools/$toolId/': typeof AppConnectorsIdToolsToolIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/api-keys'
    | '/approvals'
    | '/reauth'
    | '/servers'
    | '/status'
    | '/tool-calls'
    | '/login'
    | '/catalog/$slug'
    | '/connectors/import'
    | '/settings/audit'
    | '/settings/dlp'
    | '/settings/members'
    | '/settings/roles'
    | '/settings/security'
    | '/settings/service-accounts'
    | '/settings/sso'
    | '/invite/$token'
    | '/catalog/'
    | '/connectors/'
    | '/connectors/$id/history'
    | '/connectors/$id/tools/new'
    | '/connectors/$id/tools/'
    | '/connectors/$id/tools/$toolId/history'
    | '/connectors/$id/tools/$toolId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/api-keys'
    | '/approvals'
    | '/reauth'
    | '/servers'
    | '/status'
    | '/tool-calls'
    | '/login'
    | '/catalog/$slug'
    | '/connectors/import'
    | '/settings/audit'
    | '/settings/dlp'
    | '/settings/members'
    | '/settings/roles'
    | '/settings/security'
    | '/settings/service-accounts'
    | '/settings/sso'
    | '/invite/$token'
    | '/catalog'
    | '/connectors'
    | '/connectors/$id/history'
    | '/connectors/$id/tools/new'
    | '/connectors/$id/tools'
    | '/connectors/$id/tools/$toolId/history'
    | '/connectors/$id/tools/$toolId'
  id:
    | '__root__'
    | '/_app'
    | '/_public'
    | '/_app/analytics'
    | '/_app/api-keys'
    | '/_app/approvals'
    | '/_app/reauth'
    | '/_app/servers'
    | '/_app/status'
    | '/_app/tool-calls'
    | '/_public/login'
    | '/_app/'
    | '/_app/catalog/$slug'
    | '/_app/connectors/import'
    | '/_app/settings/audit'
    | '/_app/settings/dlp'
    | '/_app/settings/members'
    | '/_app/settings/roles'
    | '/_app/settings/security'
    | '/_app/settings/service-accounts'
    | '/_app/settings/sso'
    | '/_public/invite/$token'
    | '/_app/catalog/'
    | '/_app/connectors/'
    | '/_app/connectors/$id/history'
    | '/_app/connectors/$id/tools/new'
    | '/_app/connectors/$id/tools/'
    | '/_app/connectors/$id/tools/$toolId/history'
    | '/_app/connectors/$id/tools/$toolId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/api-keys': {
      id: '/_app/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof AppApiKeysRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/approvals': {
      id: '/_app/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof AppApprovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reauth': {
      id: '/_app/reauth'
      path: '/reauth'
      fullPath: '/reauth'
      preLoaderRoute: typeof AppReauthRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/servers': {
      id: '/_app/servers'
      path: '/servers'
      fullPath: '/servers'
      preLoaderRoute: typeof AppServersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/status': {
      id: '/_app/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof AppStatusRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tool-calls': {
      id: '/_app/tool-calls'
      path: '/tool-calls'
      fullPath: '/tool-calls'
      preLoaderRoute: typeof AppToolCallsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_app/catalog/': {
      id: '/_app/catalog/'
      path: '/catalog'
      fullPath: '/catalog/'
      preLoaderRoute: typeof AppCatalogIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalog/$slug': {
      id: '/_app/catalog/$slug'
      path: '/catalog/$slug'
      fullPath: '/catalog/$slug'
      preLoaderRoute: typeof AppCatalogSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/connectors/': {
      id: '/_app/connectors/'
      path: '/connectors'
      fullPath: '/connectors/'
      preLoaderRoute: typeof AppConnectorsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/connectors/import': {
      id: '/_app/connectors/import'
      path: '/connectors/import'
      fullPath: '/connectors/import'
      preLoaderRoute: typeof AppConnectorsImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/audit': {
      id: '/_app/settings/audit'
      path: '/settings/audit'
      fullPath: '/settings/audit'
      preLoaderRoute: typeof AppSettingsAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/dlp': {
      id: '/_app/settings/dlp'
      path: '/settings/dlp'
      fullPath: '/settings/dlp'
      preLoaderRoute: typeof AppSettingsDlpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/members': {
      id: '/_app/settings/members'
      path: '/settings/members'
      fullPath: '/settings/members'
      preLoaderRoute: typeof AppSettingsMembersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/roles': {
      id: '/_app/settings/roles'
      path: '/settings/roles'
      fullPath: '/settings/roles'
      preLoaderRoute: typeof AppSettingsRolesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/security': {
      id: '/_app/settings/security'
      path: '/settings/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AppSettingsSecurityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/service-accounts': {
      id: '/_app/settings/service-accounts'
      path: '/settings/service-accounts'
      fullPath: '/settings/service-accounts'
      preLoaderRoute: typeof AppSettingsServiceAccountsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/sso': {
      id: '/_app/settings/sso'
      path: '/settings/sso'
      fullPath: '/settings/sso'
      preLoaderRoute: typeof AppSettingsSsoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_public/invite/$token': {
      id: '/_public/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof PublicInviteTokenRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_app/connectors/$id/history': {
      id: '/_app/connectors/$id/history'
      path: '/connectors/$id/history'
      fullPath: '/connectors/$id/history'
      preLoaderRoute: typeof AppConnectorsIdHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/connectors/$id/tools/': {
      id: '/_app/connectors/$id/tools/'
      path: '/connectors/$id/tools'
      fullPath: '/connectors/$id/tools/'
      preLoaderRoute: typeof AppConnectorsIdToolsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/connectors/$id/tools/new': {
      id: '/_app/connectors/$id/tools/new'
      path: '/connectors/$id/tools/new'
      fullPath: '/connectors/$id/tools/new'
      preLoaderRoute: typeof AppConnectorsIdToolsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/connectors/$id/tools/$toolId/': {
      id: '/_app/connectors/$id/tools/$toolId/'
      path: '/connectors/$id/tools/$toolId'
      fullPath: '/connectors/$id/tools/$toolId/'
      preLoaderRoute: typeof AppConnectorsIdToolsToolIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/connectors/$id/tools/$toolId/history': {
      id: '/_app/connectors/$id/tools/$toolId/history'
      path: '/connectors/$id/tools/$toolId/history'
      fullPath: '/connectors/$id/tools/$toolId/history'
      preLoaderRoute: typeof AppConnectorsIdToolsToolIdHistoryRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppApiKeysRoute: typeof AppApiKeysRoute
  AppApprovalsRoute: typeof AppApprovalsRoute
  AppReauthRoute: typeof AppReauthRoute
  AppServersRoute: typeof AppServersRoute
  AppStatusRoute: typeof AppStatusRoute
  AppToolCallsRoute: typeof AppToolCallsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCatalogSlugRoute: typeof AppCatalogSlugRoute
  AppConnectorsImportRoute: typeof AppConnectorsImportRoute
  AppSettingsAuditRoute: typeof AppSettingsAuditRoute
  AppSettingsDlpRoute: typeof AppSettingsDlpRoute
  AppSettingsMembersRoute: typeof AppSettingsMembersRoute
  AppSettingsRolesRoute: typeof AppSettingsRolesRoute
  AppSettingsSecurityRoute: typeof AppSettingsSecurityRoute
  AppSettingsServiceAccountsRoute: typeof AppSettingsServiceAccountsRoute
  AppSettingsSsoRoute: typeof AppSettingsSsoRoute
  AppCatalogIndexRoute: typeof AppCatalogIndexRoute
  AppConnectorsIndexRoute: typeof AppConnectorsIndexRoute
  AppConnectorsIdHistoryRoute: typeof AppConnectorsIdHistoryRoute
  AppConnectorsIdToolsNewRoute: typeof AppConnectorsIdToolsNewRoute
  AppConnectorsIdToolsIndexRoute: typeof AppConnectorsIdToolsIndexRoute
  AppConnectorsIdToolsToolIdHistoryRoute: typeof AppConnectorsIdToolsToolIdHistoryRoute
  AppConnectorsIdToolsToolIdIndexRoute: typeof AppConnectorsIdToolsToolIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppApiKeysRoute: AppApiKeysRoute,
  AppApprovalsRoute: AppApprovalsRoute,
  AppReauthRoute: AppReauthRoute,
  AppServersRoute: AppServersRoute,
  AppStatusRoute: AppStatusRoute,
  AppToolCallsRoute: AppToolCallsRoute,
  AppIndexRoute: AppIndexRoute,
  AppCatalogSlugRoute: AppCatalogSlugRoute,
  AppConnectorsImportRoute: AppConnectorsImportRoute,
  AppSettingsAuditRoute: AppSettingsAuditRoute,
  AppSettingsDlpRoute: AppSettingsDlpRoute,
  AppSettingsMembersRoute: AppSettingsMembersRoute,
  AppSettingsRolesRoute: AppSettingsRolesRoute,
  AppSettingsSecurityRoute: AppSettingsSecurityRoute,
  AppSettingsServiceAccountsRoute: AppSettingsServiceAccountsRoute,
  AppSettingsSsoRoute: AppSettingsSsoRoute,
  AppCatalogIndexRoute: AppCatalogIndexRoute,
  AppConnectorsIndexRoute: AppConnectorsIndexRoute,
  AppConnectorsIdHistoryRoute: AppConnectorsIdHistoryRoute,
  AppConnectorsIdToolsNewRoute: AppConnectorsIdToolsNewRoute,
  AppConnectorsIdToolsIndexRoute: AppConnectorsIdToolsIndexRoute,
  AppConnectorsIdToolsToolIdHistoryRoute:
    AppConnectorsIdToolsToolIdHistoryRoute,
  AppConnectorsIdToolsToolIdIndexRoute: AppConnectorsIdToolsToolIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PublicRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
  PublicInviteTokenRoute: typeof PublicInviteTokenRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
  PublicInviteTokenRoute: PublicInviteTokenRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
